### ISSUE TITLE
Поиск

### ISSUE THREAD

**Issue by toyrik** [Longbeardsoft/currentdishupravosloaviem#12]
Настроить отображение формы поиска. Настрить её размер таким образом что бы она гармонично смотрелась в соотношении с другими элементами

**Comment by toyrik** [comment]
По идее это надо редактировать в режиме подключения.

**Comment by toyrik** [comment]
Ну в том смысле что отображение формы стилизуется в яндексе, можно конекчно написать своих стилей, но работать они не будут потому как яндекс подгружает !important.

**Comment by DmitriyDolinov** [comment]
Да, эт надо отдельный поиск искать, там, что можно я настроил

**Comment by toyrik** [comment]
Как вариант, можно сделать дополнительную обёртку которой задать необходимые стили
